const MIN_START_DATE_ISO = '2025-01-01T00:00:00.000Z';

const PRODUCT_ALIAS = Object.freeze({
  MP_CONILON: 'MP_CONILON',
  ACABADO_RANCHO_10X500: 'ACABADO_RANCHO_10X500',
  ACABADO_RANCHO_20X250: 'ACABADO_RANCHO_20X250',
  ACABADO_NOVAERA_10X500: 'ACABADO_NOVAERA_10X500',
});

const PRODUCT_NORMALIZATION_MAP = Object.freeze({
  MP_CONILON: [
    'CAFE CONILON BENEFICIADO',
    'CAFE CONILON BENEFICIADO KG',
    'CAFE CONILON BENEFICIADO SC',
    'CAFE CONILON BENEFICIADO EM GRAO CRU',
    'CAFE CONILON BENEFICIADO GRAO CRU',
    'CAFE CONILON BENEFICIADO EM GRAO CRU PARA INDUSTRIALIZACAO',
    'CAFÉ CONILON BENEFICIADO GRÃO CRU',
    'Cafe Conilon Beneficiado em Grao',
    'CAFE CONILON',
    'CAFE CONILLON BENEFICIADO NAO TORRADO',
    'CAFE CONILLON BENEFICIADO EM GRAO CRU PARA INDUSTRIALIZACAO',
    'CAFE CANILON GRAO CRU',
  ],
  ACABADO_RANCHO_10X500: [
    'CAFE DO RANCHO 10X500',
  ],
  ACABADO_RANCHO_20X250: [
    'CAFE DO RANCHO 20X250',
  ],
  ACABADO_NOVAERA_10X500: [
    'CAFE NOVA ERA 10X500',
  ],
});

const CONSUMPTION_RATIO_SC_PER_UNIT = 1 / 9.6;

const BLOCKED_CNPJS = [
  '26246301000193',
  '18135191000164',
];

const TARGET_COMPANY_MATCHERS = Object.freeze([
  {
    alias: 'JM',
    nameTokens: ['JM', 'ALIMENTOS'],
  },
  {
    alias: 'OLG',
    nameTokens: ['OLG', 'INDUSTRIA'],
  },
]);

const INITIAL_STOCK_SC = 1000;
const INITIAL_COST_PER_SC = 1800;

module.exports = {
  MIN_START_DATE_ISO,
  PRODUCT_ALIAS,
  PRODUCT_NORMALIZATION_MAP,
  CONSUMPTION_RATIO_SC_PER_UNIT,
  BLOCKED_CNPJS,
  TARGET_COMPANY_MATCHERS,
  INITIAL_STOCK_SC,
  INITIAL_COST_PER_SC,
};
