-- Add detailed tax fields per item
ALTER TABLE "InvoiceItem" ADD COLUMN "vBC" DECIMAL(65,30);
ALTER TABLE "InvoiceItem" ADD COLUMN "vICMS" DECIMAL(65,30);
ALTER TABLE "InvoiceItem" ADD COLUMN "vICMSDeson" DECIMAL(65,30);
ALTER TABLE "InvoiceItem" ADD COLUMN "vBCST" DECIMAL(65,30);
ALTER TABLE "InvoiceItem" ADD COLUMN "vST" DECIMAL(65,30);
ALTER TABLE "InvoiceItem" ADD COLUMN "vTotTrib" DECIMAL(65,30);
